name: datacomp
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - aiofiles=22.1.0
  - aiosqlite=0.18.0
  - anyio=3.5.0
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.0.5
  - babel=2.11.0
  - backcall=0.2.0
  - bleach=4.1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2023.08.22
  - certifi=2023.11.17
  - cffi=1.15.1
  - debugpy=1.6.7
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - exceptiongroup=1.0.4
  - executing=0.8.3
  - idna=3.4
  - ipykernel=6.25.0
  - ipython=8.15.0
  - ipython_genutils=0.2.0
  - jedi=0.18.1
  - jinja2=3.1.2
  - json5=0.9.6
  - jsonschema=4.19.2
  - jsonschema-specifications=2023.7.1
  - jupyter_client=7.4.9
  - jupyter_core=5.5.0
  - jupyter_events=0.8.0
  - jupyter_server=1.23.4
  - jupyter_server_fileid=0.9.0
  - jupyter_server_ydoc=0.8.0
  - jupyter_ydoc=0.2.4
  - jupyterlab=3.6.3
  - jupyterlab_pygments=0.2.2
  - jupyterlab_server=2.25.1
  - ld_impl_linux-64=2.38
  - libffi=3.3
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libprotobuf=3.20.1
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - markupsafe=2.1.1
  - matplotlib-inline=0.1.6
  - mistune=2.0.4
  - nbclassic=1.0.0
  - nbclient=0.8.0
  - nbconvert=7.10.0
  - nbformat=5.9.2
  - ncurses=6.3
  - nest-asyncio=1.5.6
  - notebook=6.5.4
  - notebook-shim=0.2.3
  - openssl=1.1.1w
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=22.2.2
  - platformdirs=3.10.0
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.36
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.15.1
  - pyopenssl=23.2.0
  - pysocks=1.7.1
  - python=3.10.8
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - python-json-logger=2.0.7
  - pyzmq=23.2.0
  - readline=8.2
  - referencing=0.30.2
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.10.6
  - send2trash=1.8.2
  - setuptools=65.5.0
  - six=1.16.0
  - sniffio=1.2.0
  - sqlite=3.39.3
  - stack_data=0.2.0
  - terminado=0.17.1
  - tinycss2=1.2.1
  - tk=8.6.12
  - tomli=2.0.1
  - tornado=6.3.3
  - traitlets=5.7.1
  - typing_extensions=4.7.1
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=0.58.0
  - wheel=0.37.1
  - xz=5.2.6
  - y-py=0.5.9
  - yaml=0.2.5
  - ypy-websocket=0.8.2
  - zeromq=4.3.4
  - zlib=1.2.13
  - pip:
    - absl-py==1.3.0
    - aiohttp==3.8.3
    - aioitertools==0.11.0
    - aiosignal==1.3.1
    - albumentations==1.3.0
    - astunparse==1.6.3
    - async-timeout==4.0.2
    - attrs==22.1.0
    - azure-core==1.26.1
    - azure-storage-blob==12.14.1
    - beautifulsoup4==4.11.1
    - biterm==0.1.5
    - boto3==1.34.25
    - botocore==1.34.25
    - braceexpand==0.1.7
    - cachetools==5.2.0
    - charset-normalizer==2.1.1
    - click==8.1.3
    - clip==1.0
    - clip-benchmark==1.4.0
    - cloudflare==2.19.2
    - cloudpathlib==0.13.0
    - colorama==0.4.4
    - comm==0.2.1
    - contextlib2==21.6.0
    - contourpy==1.0.7
    - cramjam==2.8.1
    - cryptography==39.0.2
    - cycler==0.11.0
    - cython==3.0.8
    - dataclasses==0.6
    - datasets==2.8.0
    - dill==0.3.6
    - dm-tree==0.1.7
    - docker-pycreds==0.4.0
    - docopt==0.6.2
    - docutils==0.16
    - etils==0.9.0
    - exifread-nocycle==3.0.1
    - fasttext==0.9.2
    - fasttext-langdetect==1.0.3
    - filelock==3.8.0
    - fire==0.4.0
    - flatbuffers==22.10.26
    - fonttools==4.39.2
    - frozenlist==1.3.3
    - fsspec==2022.11.0
    - ftfy==6.1.1
    - funcy==2.0
    - gast==0.4.0
    - gcld3==3.0.13
    - gdown==4.5.3
    - gensim==4.3.2
    - gitdb==4.0.9
    - gitpython==3.1.29
    - google-api-core==2.11.0
    - google-auth==2.14.1
    - google-auth-oauthlib==0.4.6
    - google-cloud-core==2.3.2
    - google-cloud-storage==2.7.0
    - google-crc32c==1.5.0
    - google-pasta==0.2.0
    - google-resumable-media==2.4.0
    - googleapis-common-protos==1.57.0
    - grpcio==1.50.0
    - h5py==3.7.0
    - huggingface-hub==0.14.1
    - imageio==2.22.4
    - img2dataset==1.40.0
    - importlib-metadata==7.1.0
    - importlib-resources==5.10.0
    - internetarchive==3.7.0
    - ip2location==8.10.2
    - ipywidgets==8.1.1
    - iso-639==0.4.5
    - isodate==0.6.1
    - jmespath==1.0.1
    - joblib==1.2.0
    - jsonlines==4.0.0
    - jsonpatch==1.33
    - jsonpointer==2.4
    - jupyterlab-widgets==3.0.9
    - kaleido==0.2.1
    - keras==2.11.0
    - keras-preprocessing==1.1.2
    - kiwisolver==1.4.4
    - langdetect==1.0.9
    - lda==3.0.0
    - libclang==14.0.6
    - littleutils==0.2.2
    - markdown==3.4.1
    - matplotlib==3.7.1
    - mock==4.0.3
    - msrest==0.7.1
    - multidict==6.0.3
    - multiprocess==0.70.14
    - networkx==2.8.8
    - nltk==3.8.1
    - numexpr==2.9.0
    - numpy==1.25.2
    - nvidia-cublas-cu11==11.10.3.66
    - nvidia-cuda-nvrtc-cu11==11.7.99
    - nvidia-cuda-runtime-cu11==11.7.99
    - nvidia-cudnn-cu11==8.5.0.96
    - oauthlib==3.2.2
    - ogb==1.3.5
    - open-clip-torch==2.16.1
    - opencv-python==4.6.0.66
    - opencv-python-headless==4.6.0.66
    - opt-einsum==3.3.0
    - outdated==0.2.2
    - packaging==21.3
    - pandas==1.5.1
    - pathtools==0.1.2
    - patsy==0.5.3
    - pillow==9.3.0
    - plotly==5.13.1
    - promise==2.3
    - protobuf==3.20.2
    - psutil==5.9.4
    - pyarrow==15.0.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pybind11==2.10.1
    - pycld3==0.22
    - pycocoevalcap==1.2
    - pycocotools==2.0.7
    - pyldavis==3.4.1
    - pyparsing==3.0.9
    - pyphen==0.14.0
    - pysimdjson==5.0.2
    - pytz==2022.6
    - pywavelets==1.4.1
    - pyyaml==5.3.1
    - qudida==0.0.4
    - regex==2022.10.31
    - requests==2.28.1
    - requests-file==1.5.1
    - requests-oauthlib==1.3.1
    - responses==0.18.0
    - rsa==4.7.2
    - s3transfer==0.10.0
    - schema==0.7.5
    - scikit-image==0.19.3
    - scikit-learn==1.1.3
    - scipy==1.9.3
    - seaborn==0.13.1
    - sentencepiece==0.1.97
    - sentry-sdk==1.11.1
    - setproctitle==1.3.2
    - shortuuid==1.0.11
    - smart-open==7.0.1
    - smmap==5.0.0
    - soupsieve==2.3.2.post1
    - statsmodels==0.13.5
    - tenacity==8.2.2
    - termcolor==2.1.0
    - textstat==0.7.3
    - threadpoolctl==3.1.0
    - tifffile==2022.10.10
    - timm==0.6.11
    - tldextract==5.1.1
    - tokenizers==0.13.2
    - toml==0.10.2
    - torch==1.13.0
    - torchvision==0.14.0
    - tqdm==4.64.1
    - transformers==4.24.0
    - typeguard==2.13.3
    - typing-extensions==4.4.0
    - tzdata==2024.1
    - urllib3==1.26.12
    - wandb==0.12.21
    - wayback==0.4.5
    - webdataset==0.2.31
    - werkzeug==2.2.2
    - wget==3.2
    - widgetsnbextension==4.0.9
    - wilds==2.0.0
    - wordcloud==1.9.3
    - wrapt==1.14.1
    - xxhash==3.2.0
    - yarl==1.8.2
    - zipp==3.10.0
